name: Build & Deploy Spring application

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build & Deploy Spring boot application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      # - name: Unit Tests
      #   run: mvn -B test --file backend/pom.xml

      - name: Build the application
        run:
          ./mvnw clean 
          ./mvnw -B package --file backend/pom.xml
